version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka1:29090
      - KAFKA_LISTENERS=PLAINTEXT://:9092,INTERNAL://:29090
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka2:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093,INTERNAL://kafka2:29090
      - KAFKA_LISTENERS=PLAINTEXT://:9093,INTERNAL://:29090
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  hello1:
    build: .
    environment:
      - KAFKA_SERVERS=kafka1:29090,kafka2:29090
    depends_on:
      - kafka1
      - kafka2
    networks:
      - kafka-net
  hello2:
    build: .
    environment:
      - KAFKA_SERVERS=kafka1:29090,kafka2:29090
    depends_on:
      - kafka1
      - kafka2
    networks:
      - kafka-net
  hello3:
    build: .
    environment:
      - KAFKA_SERVERS=kafka1:29090,kafka2:29090
    depends_on:
      - kafka1
      - kafka2
    networks:
      - kafka-net
  hello4:
    build: .
    environment:
      - KAFKA_SERVERS=kafka1:29090,kafka2:29090
    depends_on:
      - kafka1
      - kafka2
    networks:
      - kafka-net
networks:
    kafka-net:
        driver: bridge

volumes:
  kafka_data:
    driver: local
  kafka2_data:
    driver: local
  kafka3_data:
    driver: local